# Generated by Django 4.0.3 on 2023-06-08 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_rest', '0002_automobile_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autos', to='inventory_rest.vehiclemodel'),
        ),
    ]
